#!/usr/bin/env python3
import os
import subprocess

from string import Template

from util import get_project_root_directory

ROOT_DIR = None
CODEGEN_DIR = None
TEMPLATE_DIR = None
TARGET_DIR = None
HEADER_DIR = None
SOURCE_DIR = None

written_files = []


def camel_to_snake(identifier):
    return "".join( 
        f"{'' if c.islower() else '_' if i != 0 else '' }{c.lower()}" 
        for i, c in enumerate(identifier) 
    )

def sanitized_enum_values(lines):
    for line in lines:
        e_val = line.strip()
        if not e_val.isidentifier():
            raise Exception(f"Malformed enum value encountered during codegen: {e_val}")
        yield e_val

def codegen_for_enum(target_file_lines):
    """
    Full list of variables to substitute:
        CODEGEN_MESSAGE
        ENUM_NAME
        ENUM_VALUES
        SNAKE_CASE_ENUM_NAME
        HEADER_FILE
        ENUM_STRING_VALUES
        ENUM_VECTOR_VALUES
    """

    header_template_file = f"{TEMPLATE_DIR}/enum_header.template"
    source_template_file = f"{TEMPLATE_DIR}/enum_source.template"

    first_line = target_file_lines[0]
    rest = target_file_lines[1:]
    enum_values = list(sanitized_enum_values(rest))

    ENUM_NAME = first_line.split()[1].strip()
    HEADER_FILE = f"{ENUM_NAME.lower()}.h"
    SNAKE_CASE_ENUM_NAME = camel_to_snake(ENUM_NAME)

    ENUM_VALUES = "\n".join( f"{ev}," for ev in enum_values)
    ENUM_STRING_VALUES = "\n".join( f"\"{ev}\"," for ev in enum_values)
    ENUM_VECTOR_VALUES = "\n".join( f"{ENUM_NAME}::{ev}," for ev in enum_values)

    CODEGEN_MESSAGE=f"""/*
*    THIS FILE WAS GENERATED BY {os.path.basename(__file__)}
*       
*    ANY MODIFICATIONS WILL BE CLOBBERED BY THE NEXT CODEGEN RUN.
*    DO NOT EDIT THIS FILE DIRECTLY, MODIFY THE TARGET OR TEMPLATE FILES 
*    INSTEAD.
* */
"""

    header_output_file = f"{HEADER_DIR}/{HEADER_FILE}"
    source_output_file = f"{SOURCE_DIR}/{ENUM_NAME.lower()}.cpp"

    variables = {
        "CODEGEN_MESSAGE": CODEGEN_MESSAGE,
        "ENUM_NAME": ENUM_NAME,
        "ENUM_VALUES": ENUM_VALUES,
        "SNAKE_CASE_ENUM_NAME": SNAKE_CASE_ENUM_NAME,
        "HEADER_FILE": HEADER_FILE,
        "ENUM_STRING_VALUES": ENUM_STRING_VALUES,
        "ENUM_VECTOR_VALUES": ENUM_VECTOR_VALUES,
    }

    for template, output in [
        (header_template_file, header_output_file), 
        (source_template_file, source_output_file)
    ]:
        with open(template) as f:
            src = Template(f.read())
            result = src.substitute(variables)
            with open(output, 'w') as output_file: 
                output_file.write(result)
            written_files.append(output)


def codegen_target_file(target_file):

    with open(f"{TARGET_DIR}/{target_file}") as tf:
        lines = tf.readlines()
        if len(lines) > 0:
            first_line = lines[0]
            if first_line.startswith("enum"):
                codegen_for_enum(lines)
                return
        
    raise Exception(f"Ecountered malformed target file during codegen: {target_file}")


def codegen_all():
    for target_file in os.listdir(TARGET_DIR):
        codegen_target_file(target_file)

def format_files():
    subprocess.run([
            "clang-format",
            "-i",
            # "--style=file",
            *written_files
        ]
    )

def main():
    global ROOT_DIR
    global CODEGEN_DIR
    global TEMPLATE_DIR
    global TARGET_DIR
    global HEADER_DIR
    global SOURCE_DIR

    ROOT_DIR = get_project_root_directory()
    CODEGEN_DIR = f"{ROOT_DIR}/codegen"
    TEMPLATE_DIR = f"{CODEGEN_DIR}/templates"
    TARGET_DIR =  f"{CODEGEN_DIR}/targets"
    HEADER_DIR = f"{ROOT_DIR}/include"
    SOURCE_DIR = ROOT_DIR

    codegen_all()
    format_files()

    print("Generated the following files:") 
    for full_file_path in written_files:
        print(f"    {full_file_path}")
    print()

if __name__ == "__main__":
    main()