/*
 *    THIS FILE WAS GENERATED BY codegen.py
 *
 *    ANY MODIFICATIONS WILL BE CLOBBERED BY THE NEXT CODEGEN RUN.
 *    DO NOT EDIT THIS FILE DIRECTLY, MODIFY THE TARGET OR TEMPLATE FILES
 *    INSTEAD.
 * */

#include <string>
#include <vector>

#include "nodetype.h"

using std::string;
using std::vector;

string node_type_to_string(NodeType e) {
  vector<string> values{
      "TOP_LEVEL",
      "BLOCK",
      "ASSIGN_OP",
      "VAR_DECLARE",
      "FUNC_DECLARE",
      "MODULE_IMPORT",
      "IF",
      "RETURN",
      "WHILE",
      "BINARY_OP",
      "UNARY_OP",
      "FUNC_CALL",
      "INDEX_ACCESS",
      "FIELD_ACESS",
      "VAR_LOOKUP",
      "EXPR_LIST",
      "BUILTIN_PRINT",
      "BUILTIN_VECTOR_LENGTH",
      "BUILTIN_VECTOR_APPEND",
      "BUILTIN_STRING_LENGTH",
      "BUILTIN_DICT_LENGTH",
      "BUILTIN_DICT_KEYS",
      "BUILTIN_DICT_CONTAINS",
      "VEC_LITERAL",
      "DICT_LITERAL",
      "BOOL_LITERAL",
      "INT_LITERAL",
      "FLOAT_LITERAL",
      "STRING_LITERAL",
      "NOTHING_LITERAL",
  };
  return values.at((int)e);
}

NodeType int_to_node_type(int i) {
  vector<NodeType> values{
      NodeType::TOP_LEVEL,
      NodeType::BLOCK,
      NodeType::ASSIGN_OP,
      NodeType::VAR_DECLARE,
      NodeType::FUNC_DECLARE,
      NodeType::MODULE_IMPORT,
      NodeType::IF,
      NodeType::RETURN,
      NodeType::WHILE,
      NodeType::BINARY_OP,
      NodeType::UNARY_OP,
      NodeType::FUNC_CALL,
      NodeType::INDEX_ACCESS,
      NodeType::FIELD_ACESS,
      NodeType::VAR_LOOKUP,
      NodeType::EXPR_LIST,
      NodeType::BUILTIN_PRINT,
      NodeType::BUILTIN_VECTOR_LENGTH,
      NodeType::BUILTIN_VECTOR_APPEND,
      NodeType::BUILTIN_STRING_LENGTH,
      NodeType::BUILTIN_DICT_LENGTH,
      NodeType::BUILTIN_DICT_KEYS,
      NodeType::BUILTIN_DICT_CONTAINS,
      NodeType::VEC_LITERAL,
      NodeType::DICT_LITERAL,
      NodeType::BOOL_LITERAL,
      NodeType::INT_LITERAL,
      NodeType::FLOAT_LITERAL,
      NodeType::STRING_LITERAL,
      NodeType::NOTHING_LITERAL,
  };
  return values.at(i);
}
