/*
 *    THIS FILE WAS GENERATED BY codegen.py
 *
 *    ANY MODIFICATIONS WILL BE CLOBBERED BY THE NEXT CODEGEN RUN.
 *    DO NOT EDIT THIS FILE DIRECTLY, MODIFY THE TARGET OR TEMPLATE FILES
 *    INSTEAD.
 * */

#include <string>
#include <vector>

#include "tokentype.h"

using std::string;
using std::vector;

string token_type_to_string(TokenType e) {
  vector<string> values{
      "FUNCTION",
      "IMPORT",
      "AS",
      "LET",
      "CONST",
      "IF",
      "ELSEIF",
      "ELSE",
      "WHILE",
      "RETURN",
      "IDENTIFIER",
      "DOT",
      "DOT_DOT",
      "COMMA",
      "EQUALS",
      "EQUALS_EQUALS",
      "NOT",
      "NOT_EQUALS",
      "LESS",
      "LESS_EQUALS",
      "GREATER",
      "GREATER_EQUALS",
      "PLUS",
      "PLUS_EQUALS",
      "AND",
      "OR",
      "MINUS",
      "MINUS_EQUALS",
      "TIMES",
      "TIMES_EQUALS",
      "DIV",
      "DIV_EQUALS",
      "MOD",
      "MOD_EQUALS",
      "LPAREN",
      "RPAREN",
      "LBRACKET",
      "RBRACKET",
      "LBRACE",
      "RBRACE",
      "COLON",
      "SEMICOLON",
      "BOOL_LITERAL",
      "INT_LITERAL",
      "FLOAT_LITERAL",
      "STRING_LITERAL",
      "NOTHING_LITERAL",
      "END_OF_FILE",
      "NULL_TOKEN",
  };
  return values.at((int)e);
}

TokenType int_to_token_type(int i) {
  vector<TokenType> values{
      TokenType::FUNCTION,
      TokenType::IMPORT,
      TokenType::AS,
      TokenType::LET,
      TokenType::CONST,
      TokenType::IF,
      TokenType::ELSEIF,
      TokenType::ELSE,
      TokenType::WHILE,
      TokenType::RETURN,
      TokenType::IDENTIFIER,
      TokenType::DOT,
      TokenType::DOT_DOT,
      TokenType::COMMA,
      TokenType::EQUALS,
      TokenType::EQUALS_EQUALS,
      TokenType::NOT,
      TokenType::NOT_EQUALS,
      TokenType::LESS,
      TokenType::LESS_EQUALS,
      TokenType::GREATER,
      TokenType::GREATER_EQUALS,
      TokenType::PLUS,
      TokenType::PLUS_EQUALS,
      TokenType::AND,
      TokenType::OR,
      TokenType::MINUS,
      TokenType::MINUS_EQUALS,
      TokenType::TIMES,
      TokenType::TIMES_EQUALS,
      TokenType::DIV,
      TokenType::DIV_EQUALS,
      TokenType::MOD,
      TokenType::MOD_EQUALS,
      TokenType::LPAREN,
      TokenType::RPAREN,
      TokenType::LBRACKET,
      TokenType::RBRACKET,
      TokenType::LBRACE,
      TokenType::RBRACE,
      TokenType::COLON,
      TokenType::SEMICOLON,
      TokenType::BOOL_LITERAL,
      TokenType::INT_LITERAL,
      TokenType::FLOAT_LITERAL,
      TokenType::STRING_LITERAL,
      TokenType::NOTHING_LITERAL,
      TokenType::END_OF_FILE,
      TokenType::NULL_TOKEN,
  };
  return values.at(i);
}
